apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: express-roll
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
        - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
          name: express
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
  minReadySeconds: 30
  strategy:
    canary:
      analysis:
        templates:
          - templateName: pass-always
        startingStep: 1 # delay starting analysis run until setWeight: 40%
      steps:
        - setWeight: 25
        - pause: {duration: 30s}
        - analysis:
            templates:
            - templateName: mixed-tests
        - experiment:
            duration: 15s
            templates:
            - name: canary
              specRef: canary
            # This experiment performs its own analysis by referencing one or more AnalysisTemplates
            # here. The success or failure of these runs will progress or abort the rollout respectively.
            analyses:
            - name: random-fail-experiment
              templateName: mixed-tests-experiment
              requiredForCompletion: true
